### ISSUE TITLE
What is the use case of this app , pls explain 

### ISSUE THREAD

**Issue by chechani** [kid1194/frappe-strict-session-defaults#1]
Whether Frappe Session Defaults can be used for permission control like filter records based on user etc

**Comment by kid1194** [comment]
@chechani No. I created this plugin for someone to enforce setting the session defaults on login for specific users or roles..

**Comment by flexy2ky** [comment]
I am trying to test the app to see if I could use it to solve a specific issue with sessions but i wasn't able to install it as it threw an error. Opened an issue for it with full traceback.

**Comment by kid1194** [comment]
@flexy2ky I have replied to you..
